backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "static"
    label: "Static (Videos)"
    folder: "_static"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "YouTube URL", name: "youtube_url", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}

  - name: "leaks"
    label: "Leaks (Research)"
    folder: "_leaks"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Document Link", name: "document_url", widget: "string"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Document Type", name: "doc_type", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}

  - name: "echoes"
    label: "Echoes (Art)"
    folder: "_echoes"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Artist Name", name: "artist", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Artist Info", name: "artist_info", widget: "text", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
